name: 'similar-contributions'
description: 'Searches for similar contributions by comparing previous pull requests to the current proposal title'

inputs:
  search_dir:
    description: Directory containing the contributions
    required: true
    default: "attic"
  filter:
    description: Filter for contribution types that are supposed to be regarded
    required: true
    default: "['essay', 'course-automation', 'demo', 'presentation', 'executable-tutorial', 'tutorial', 'open-source', 'open']"

runs:
  using: "composite"
  steps:
    - run: |
        echo "${{ inputs.search_dir }}"
        echo "${{ inputs.filter }}"
      shell: bash
    - run: python -m pip install nltk  # Installing dependencies
      shell: bash
    #- run: echo Your action_path: ${{ github.action_path }}
    #  shell: bash
    #- run: echo Your github.workspace: ${{ github.workspace }}
    #  shell: bash
    - run: python ./main.py
      env: |
        INPUT_SEARCH_DIR: "${{ inputs.search_dir }}"
        INPUT_FILTER: "${{ inputs.filter }}"
      shell: bash

    # Set env according to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
    - name: Read generated comment into env
      run: |
        echo 'GENERATED_COMMENT<<EOF' >> $GITHUB_ENV
        cat $GITHUB_WORKSPACE/generated_comment.md >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash
